// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rglaszkaqbagpbtursjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbGFzemthcWJhZ3BidHVyc2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODU0ODUsImV4cCI6MjA2OTI2MTQ4NX0.ujbPJ2XqGyWS313D2PLGGxs1g8OJLdIw2qmID6Ift-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});